### PR TITLE
email to M6

### PR DESCRIPTION
**Pull request by sdelamo**

### CODE REVIEW

**Comment by graemerocher** [comment]
tests are failing?

**Comment by sdelamo** [comment]
> tests are failing?

Yes, a test started failing after the upgrade. That it is why I left it as draft. I will review to see if I can figure out why it is failing.

**Comment by sdelamo** [comment]
> > tests are failing?
> 
> Yes, a test started failing after the upgrade. That it is why I left it as draft. I will review to see if I can figure out why it is failing.


I had to change [a test to use Micronaut HTTP Client JDK instead of the Micronaut HTTP Client Netty impelmenation](https://github.com/micronaut-projects/micronaut-email/pull/216/commits/c867b6ca7db35da3a082cd1bfb1b88e0b1e5faf5). The test serialises parts of the [Mailhog](https://github.com/mailhog/MailHog) JSON response  to a POJO.

Otherwise, this test will fail: 

```bash
./gradlew :micronaut-email-javamail:test --tests "io.micronaut.email.javamail.JavaMailBodyAndAttachmentSpec.can send an email from #desc contact details"
```

@yawkat do you know what could be the culprit?

**Review by wetted — APPROVED** [review]

**Review by graemerocher — APPROVED** [review]

**Comment by yawkat** [comment]
need to add text/json support

**Pull request merged**
