### PR TITLE
Adds support to specify custom email headers.

### PR DESCRIPTION
**Pull request by satai**
If this concept is OK I would add similar code to missing Composers.

### CODE REVIEW

**Comment by sdelamo** [comment]
The API already contains methods which take a `Consumer` so that you can set headers or any other custom field. 

https://micronaut-projects.github.io/micronaut-email/latest/api/io/micronaut/email/EmailSender.html#send-io.micronaut.email.Email.Builder-java.util.function.Consumer-

You can already do: 

```
email.send(emailBuilder, message -> {
 for (Map.Entry<String, List<String>> entry : headers.entrySet()) {
                 for (String value : entry.getValue()) {
                     message.addHeader(entry.getKey(), value);
                 }
             }
})```

I think we don't need this PR. Will the above API fullfil your needs?

**Comment by satai** [comment]
@sdelamo The (client) code looks uglier with it, but it should do the trick. I will test it for my usecase.

Thanks for pointing me this direction.

**Comment by sdelamo** [comment]
Closing this for now. Let me know if it does not work.

**Comment by satai** [comment]
I worked like a charm, thanks a lot @sdelamo

**Pull request closed without merging**
